import pygame
from mingus.containers import *
import mingus.extra.lilypond as LilyPond
from mingus.midi import midi_file_out
from src.ca.qc.bdeb.sim204.smartsounds.generationMusique.ConvertisseurMidi import ConvertisseurMidi

from resources import directory

from_Track_Orig = LilyPond.from_Track


# Cette méthode est tirée de Stack Overflow : https://stackoverflow.com/questions/66215400/how-to-change-the-clef-of-a-container-in-mingus
def from_track(track):
    global from_Track_Orig
    result = from_Track_Orig(track)
    if isinstance(result, str) and track.instrument is not None and isinstance(track.instrument.clef, str):
        result = r"%s \clef %s %s" % (result[:1], track.instrument.clef.split()[0], result[1:])
    return result


def generer_partition():
    LilyPond.from_Track = from_track

    i = Instrument()

    chord = NoteContainer(["C-2", "C-3"])
    chord2 = NoteContainer(["E-4", "G-4", "C-5"])
    chord3 = NoteContainer(["F-4", "A-4", "C-5"])
    chord4 = NoteContainer(["D-4", "F-4", "G-4", "B-4"])
    chord5 = NoteContainer(["C-4", "E-4", "G-4", "C-5"])

    b = Bar("C", (4, 4))
    b2 = Bar("C", (4, 4))
    b3 = Bar("C", (4, 4))
    b4 = Bar("C", (4, 4))
    b.place_notes(chord2, 4)
    b.place_notes(chord3, 4)
    b.place_notes(chord2, 4)
    b.place_notes(chord4, 4)
    b2.place_notes(chord5, 1)
    b3.place_notes(["C-3"], 4)
    b3.place_notes(["F-3"], 4)
    b3.place_notes(["G-3"], 4)
    b3.place_notes(["G-2"], 4)
    b4.place_notes(chord, 1)

    t1 = Track()
    t2 = Track(instrument=i)
    t1.add_bar(b)
    t1.add_bar(b2)
    t2.add_bar(b3)
    t2.add_bar(b4)

    c = Composition()
    c.set_author("Generated by SmartSounds")
    c.title = 'Composition1'
    c.set_title(c.title)
    c.add_track(t1)
    c.add_track(t2)
    return c


def play_music(music_file):
    # Cette méthode est tirée de https://www.daniweb.com/programming/software-development/code/216979/embed-and-play-midi-music-in-your-code-python
    clock = pygame.time.Clock()
    pygame.mixer.music.load(music_file)
    pygame.mixer.music.play()
    while pygame.mixer.music.get_busy():
        # check if playback has finished
        clock.tick(30)


def jouer_partition(partition):
    midi = exporter_midi(partition)
    freq = 44100  # audio CD quality
    bitsize = -16  # unsigned 16 bit
    channels = 2  # 1 is mono, 2 is stereo
    buffer = 1024  # number of samples
    pygame.mixer.init(freq, bitsize, channels, buffer)
    play_music(midi)


def generer_png(partition):
    c = LilyPond.from_Composition(partition)
    LilyPond.to_png(c, partition.title)


def exporter_wav(partition):
    sf = directory.ROOT_DIR + "\\FluidR3_GM.SF2"
    midi = exporter_midi(partition)
    ConvertisseurMidi.convertir_midi(midi, sf, partition.title + ".wav")
    return midi


def exporter_midi(partition):
    midi = partition.title + ".midi"
    midi_file_out.write_Composition(midi, partition)
    return midi


def exporter_pdf(partition):
    c = LilyPond.from_Composition(partition)
    LilyPond.to_pdf(c, partition.title)
