from mingus.midi import fluidsynth
from mingus.containers import *
import mingus.extra.lilypond as LilyPond
from mingus.midi import midi_file_out
from src.ca.qc.bdeb.sim204.smartsounds.generationMusique.ConvertisseurMidi import ConvertisseurMidi

from resources import directory

from_Track_Orig = LilyPond.from_Track


# Cette méthode est tirée de Stack Overflow : https://stackoverflow.com/questions/66215400/how-to-change-the-clef-of-a-container-in-mingus
def from_track(track):
    global from_Track_Orig
    result = from_Track_Orig(track)
    if isinstance(result, str) and track.instrument is not None and isinstance(track.instrument.clef, str):
        result = r"%s \clef %s %s" % (result[:1], track.instrument.clef.split()[0], result[1:])
    return result


def generer_partition():
    LilyPond.from_Track = from_track

    i = Instrument()

    chord = NoteContainer(["C-4", "E-4", "G-4", "C-5"])
    chord2 = NoteContainer(["C-2", "C-3"])
    chord3 = NoteContainer(["C-4", "E-4", "G-4", "Bb-4"])

    b = Bar("C", (2, 4))
    b.place_notes(chord, 4)
    b.place_notes(chord3, 4)
    b2 = Bar("C", (2, 4))
    b2.place_notes(chord2, 2)

    t1 = Track()
    t2 = Track(instrument=i)
    t1.add_bar(b)
    t2.add_bar(b2)

    c = Composition()
    c.set_author("Generated by SmartSounds")
    c.title = 'Composition1'
    c.set_title(c.title)
    c.add_track(t1)
    c.add_track(t2)
    return c


def jouer_partition(partition):
    sf = directory.ROOT_DIR + "\\FluidR3_GM.SF2"
    fluidsynth.init(sf, "dsound")
    fluidsynth.play_Composition(partition)


def generer_png(partition):
    c = LilyPond.from_Composition(partition)
    LilyPond.to_png(c, partition.title)


def exporter_wav(partition):
    sf = directory.ROOT_DIR + "\\FluidR3_GM.SF2"
    midi = exporter_midi(partition)
    ConvertisseurMidi.convertir_midi(midi, sf, partition.title + ".wav")
    return midi


def exporter_midi(partition):
    midi = partition.title + ".midi"
    midi_file_out.write_Composition(midi, partition)
    return midi


def exporter_pdf(partition):
    c = LilyPond.from_Composition(partition)
    LilyPond.to_pdf(c, partition.title)
